package ch.fhnw.edu.cpib.scanner.enumerations;

import ch.fhnw.edu.cpib.scanner.Token;

public enum Terminals implements Token {
    WHILE, IDENT, RELOPR, LITERAL, SENTINEL, ADDOPR, MULTOPR, BOOLOPR, TYPE, CALL, // call
    CHANGEMOD, MECHMOD, DEBUGIN, DEBUGOUT, DO, ELSE, ENDFUN, ENDIF, ENDPROC, ENDPROGRAM, ENDWHILE, FUN, // fun
    GLOBAL, IF, FLOWMODE, INIT, LOCAL, NOTOPR, // not
    PROC, PROGRAM, MECHMODE, RETURNS, SKIP, THEN, LPAREN, // (
    RPAREN, // )
    LBRACKET, RBRACKET, COMMA, SEMICOLON, COLON, // :
    BECOMES, BOOLVALFALSE, CHANGEMODENTS, FLOWMODENTS, PARAM, PARAMNTS, PARAMLISTNTS, PARAMLIST, FUNDECLNTS, FUNDECL, TYPEDIDENT, STODECL, DECL, CPSDECLNTS, CPSDECL, GLOBALNTS, MECHMODENTS, CPSCMD, CPSCMDNTS, CMD, IFELSENTS, EXPR, EXPRNTS, TERM1, TERM1NTS, TERM2, TERM2NTS, TERM3, TERM3NTS, FACTOR, FACTORNTS, EXPRLIST, EXPRLISTLPARENNTS, EXPRLISTNTS, MONADICOPR, CASTOPR, CPSSTODECL, CPSSTODECLNTS, PROCDECL, PROCDECLNTS, BOOLVALTRUE// :=
    ;
}
